document.getElementById('year').textContent = new Date().getFullYear();
const menuBtn=document.getElementById('menuBtn');const nav=document.getElementById('nav');menuBtn.addEventListener('click',()=>nav.classList.toggle('open'));nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const fallbackSite={clinic_name:"Dr. Shikha's Homoeo Clinic",doctor_name:"Dr. Shikha Kumari Shukla",qualification:"BHMS | Homoeopathic Consultant",phone:"+91 93304 30699",whatsapp:"919330430699",address:"113 Debaipukur Road, Hindmotor, Uttarpara, West Bengal",hours:"Mon - Sat: 10:00 AM - 8:00 PM",map_link:"https://www.google.com/maps/search/?api=1&query=Dr+Shikha+Homoeo+Clinic+Hindmotor",map_embed:"https://www.google.com/maps?q=Hindmotor,Uttarpara,West+Bengal&output=embed",doctor_photo:"",about:"At Dr. Shikha's Homoeo Clinic, every patient is heard carefully. Treatment is planned according to symptoms, lifestyle, medical history and follow-up response.",experience:"5+",patients:"1000+"};
const fallbackServices=[{icon:"♀",title:"PCOS & Hormonal Imbalance",description:"Individualised care for irregular periods, acne, weight concerns and hormonal complaints."},{icon:"🦋",title:"Thyroid Disorders",description:"Supportive homoeopathic consultation for thyroid-related symptoms and wellness."},{icon:"〰",title:"Hair Fall & Dandruff",description:"Treatment planning for hair fall, scalp itching, dandruff and recurring hair concerns."},{icon:"✦",title:"Skin Allergy & Disease",description:"Care for itching, rashes, urticaria, eczema-like complaints and recurrent flare-ups."},{icon:"☉",title:"Migraine & Headache",description:"Detailed case-taking for recurring headaches, triggers and long-term management."},{icon:"🦴",title:"Arthritis & Joint Pain",description:"Support for joint stiffness, body ache, back pain and chronic pain complaints."}];
const fallbackPosts=[{date:"2026-07-05",title:"Managing seasonal cold & cough",description:"Simple supportive care tips for monsoon cough and cold season.",image:""},{date:"2026-07-01",title:"Understanding skin flare-ups",description:"Why tracking triggers helps in long-term skin care.",image:""},{date:"2026-06-28",title:"Hair fall: when to consult",description:"Common causes and when professional consultation is helpful.",image:""}];
const fallbackReviews=[{name:"Local Patient",rating:"★★★★★",text:"Very patient hearing and clear explanation of the treatment plan."},{name:"Uttarpara Patient",rating:"★★★★★",text:"Consultation felt thorough, not rushed. Good follow-up support."},{name:"Hindmotor Patient",rating:"★★★★★",text:"Helpful guidance and clear dosage instructions."}];
const fallbackGallery=["","","",""];
async function getJson(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error('missing');return await r.json()}catch(e){return fallback}}
function setText(id,value){const el=document.getElementById(id);if(el)el.textContent=value}
function setHref(id,value){const el=document.getElementById(id);if(el)el.href=value}
function applySite(s){setText('clinicNameLogo',s.clinic_name.replace(' Homoeo Clinic',''));setText('topAddress',s.address);setText('topPhone',s.phone);setText('topHours',s.hours);setText('doctorNamePlate',s.doctor_name);setText('qualificationPlate',s.qualification);setText('aboutText',s.about);setText('hoursBox',s.hours);setText('addressBox',s.address);setText('contactAddress',s.address);setText('footerClinic',s.clinic_name);setText('statExperience',s.experience);setText('statPatients',s.patients);const phoneDigits=s.phone.replace(/[^+0-9]/g,'');const wa=`https://wa.me/${s.whatsapp}?text=Hi%2C%20I%20want%20to%20book%20an%20appointment`;['heroWhatsapp','contactWhatsapp','floatWhatsapp'].forEach(id=>setHref(id,wa));['heroCall','contactPhone','floatCall'].forEach(id=>setHref(id,`tel:${phoneDigits}`));['directionBtn','contactMap','floatDirection'].forEach(id=>setHref(id,s.map_link));document.getElementById('mapFrame').src=s.map_embed||s.map_link;if(s.doctor_photo){document.getElementById('doctorPhoto').src=s.doctor_photo}}
function renderServices(items){document.getElementById('serviceGrid').innerHTML=items.map(x=>`<article class="service-card fade-up"><div class="icon">${x.icon||'🌿'}</div><h3>${x.title}</h3><p>${x.description}</p></article>`).join('')}
function renderPosts(items){document.getElementById('blogGrid').innerHTML=items.map(x=>`<article class="blog-card fade-up">${x.image?`<img src="${x.image}" alt="${x.title}">`:''}<div><small>${new Date(x.date).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}</small><h3>${x.title}</h3><p>${x.description}</p></div></article>`).join('')}
function renderReviews(items){document.getElementById('reviewGrid').innerHTML=items.map(x=>`<article class="review-card fade-up"><div class="stars">${x.rating||'★★★★★'}</div><p>“${x.text}”</p><strong>— ${x.name}</strong></article>`).join('')}
function renderGallery(items){document.getElementById('galleryGrid').innerHTML=items.map((src,i)=>src?`<img class="fade-up" src="${src}" alt="Clinic photo ${i+1}">`:`<img class="fade-up" alt="Add clinic photo ${i+1}">`).join('')}
function reveal(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.fade-up').forEach(el=>io.observe(el))}
Promise.all([getJson('/data/site.json',fallbackSite),getJson('/data/services.json',fallbackServices),getJson('/data/posts.json',fallbackPosts),getJson('/data/reviews.json',fallbackReviews),getJson('/data/gallery.json',fallbackGallery)]).then(([site,services,posts,reviews,gallery])=>{applySite(site);renderServices(services);renderPosts(posts);renderReviews(reviews);renderGallery(gallery);reveal()});
if(window.netlifyIdentity){window.netlifyIdentity.on('init',user=>{if(!user){window.netlifyIdentity.on('login',()=>{document.location.href='/admin/'})}})}
